In [1]:
import numpy as np

In [2]:
test_list = [0,1,2,3,4,5,6,7,8]
test_array = np.array(test_list).reshape((3,3))
test_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
test_array.mean(axis=0)

array([3., 4., 5.])

In [4]:
test_array.mean(axis=1)

array([1., 4., 7.])

In [8]:
list(test_array.var(axis=0))

[6.0, 6.0, 6.0]